#Requires super user
sudo: required

#Requires docker
services:
  - docker

#Steps that are required befor test or deployment
before_install:
  - docker build -t rpradhan07/docker-react -f Dockerfile.dev .

script:
  - docker run rpradhan07/docker-react npm run test -- --coverage
