#Requires super user
sudo: required

#Requires docker
services:
  - docker

#Steps that are required befor test or deployment
before_install:
  - docker build -t rpradhan07/docker-react -f Dockerfile.dev .

script:
  - docker run rpradhan07/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-969827076698"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
