version: '3'
services:
  #name of the service is web
  web:
    build:
      context: . #specify project directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: . #specify project directory
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #overriding start Command
    command: ["npm","run","test"]
